### ISSUE TITLE
There some missing files

### ISSUE THREAD

**Issue by Pined95** [arouzbehani/SapShellDesign#1]
Hi arouzbehani,

I hope you're doing well. I'm trying to work with your development project, but I've encountered some missing files. The files that appear to be missing are:

licenses.licx
Class1.cs
SAP2000v1
Tao.OpenGl.ExtensionLoader
Tao.Platform.Windows
Tao.OpenGl.Glu
Tao.FreeGlut
Tao.OpenGl

Could you please provide these files or let me know if there's a specific step I missed during the setup process?

Thank you for your help.

**Comment by arouzbehani** [comment]
Hi Pined95,

I have added them except class1.cs that was totally irrelevant, licenses.licx  is an empty file it was not used anymore
You can find missing files by following "adding some missing files" commit.

**Comment by Pined95** [comment]
Thanks so much
